set W/H 0.99
set CELLUTIL 0.7 
set CORETOIO_LEFT 8.2
set CORETOIO_BOTTOM 8.2
set CORETOIO_RIGHT 8.2
set CORETOIO_TOP 8.2

floorPlan -site HD_CoreSite -r ${W/H} ${CELLUTIL} ${CORETOIO_LEFT} ${CORETOIO_BOTTOM} ${CORETOIO_RIGHT} ${CORETOIO_TOP}